name: Hungergames
main: x0r0n.heavyhacker.hungergames.Hungergames
version: 1.0

commands:
   hungergames:
      description: Get a command overview for the Hungergames!
      usage: /Hungergames
      permission: hungergames.hungergames
      permission-message: You don't have permission.
      
permissions:
    hungergames.*:
        description: Access to all Hungergames commands!
        children:
            hungergames.hungergames: true

    hungergames.hungergames:
        description: Hungergames Command Overview
        default: true